# TARGET = invM.so
# LIBSRCS = invM_0_0.c invM_0_1.c invM_0_2.c invM_1_0.c invM_1_1.c invM_1_2.c invM_2_0.c invM_2_1.c invM_2_2.c
# LIBOBJS = $(LIBSRCS:%.c=%.o)

# all: $(TARGET)


# $(TARGET1): $(LIBOBJS) 
# 	$(CXX) $(LDFLAGS) -shared $^ -o $@ $(LIBS2)


invM.so: invM.o invM_0_0.o invM_0_1.o invM_0_2.o invM_1_0.o invM_1_1.o invM_1_2.o invM_2_0.o invM_2_1.o invM_2_2.o