function out1 = endemic_sol_S1(LAMBDA,MU,SPAN1,SPAN2,SPAN12,THETA1,THETA2)
%ENDEMIC_SOL_S1
%    OUT1 = ENDEMIC_SOL_S1(LAMBDA,MU,SPAN1,SPAN2,SPAN12,THETA1,THETA2)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    23-Dec-2021 15:24:12

t2 = SPAN1.*THETA1;
out1 = [(LAMBDA.*t2)./((MU+SPAN2.*SPAN12.*THETA2).*(MU+t2));1.0];
